version: "3"
services:
  eureka:
    image: bangjinseong/podo_gateway:${BUILD_NUMBER}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_NUMBER
    ports:
      - "9600:9600"
    environment:
      - ENCRYPT_KEY=${ENCRYPT_KEY_VALUE}
      - TZ=Asia/Seoul