server:
  port: 9600

eureka:
  client:
    service-url:
      defaultZone: http://j9d107.p.ssafy.io:9761/eureka

spring:
  application:
    name: podo-gateway-service
  cloud:
    gateway:
      routes:
        - id: podo-user-service
          uri: lb://podo-user-service    # ?? ?? URI
          predicates:                   # ?? ??? Path ?? ??
            - Path=/podo-user-service/**    # ?? Path
          filters:
            - StripPrefix=1
        - id: podo-auth-service
          uri: lb://podo-auth-service
          predicates:
            - Path=/podo-auth-service/**
          filters:
            - StripPrefix=1
  config:
    import: "optional:configserver:http://j9d107.p.ssafy.io:9900/"
    config:
      name: podo
      profile: gateway
  main:
    allow-bean-definition-overriding: true

encrypt:
  key: ${ENCRYPT_KEY}