server:
  port: 9600

eureka:
  client:
    service-url:
      defaultZone: http://j9d107.p.ssafy.io:9761/eureka

spring:
  application:
    name: podo-gateway-service
  cloud:
    gateway:
      routes:
        - id: podo-user-service
          uri: lb://podo-user-service    # ?? ?? URI
          predicates:                   # ?? ??? Path ?? ??
            - Path=/api/v1/user/**    # ?? Path
          filters:
            - StripPrefix=0
        - id: podo-auth-service
          uri: lb://podo-auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=0
        - id: podo-account-service
          uri: lb://podo-account-service
          predicates:
            - Path=/api/v1/account/**
          filters:
            - StripPrefix=0
        - id: podo-openbanking-service
          uri: lb://podo-openbanking-service
          predicates:
            - Path=/api/v1/fintech/**
          filters:
            - StripPrefix=0
    config:
      name: podo
      profile: gateway
  config:
    import: "optional:configserver:http://j9d107.p.ssafy.io:9900/"

  main:
    allow-bean-definition-overriding: true

encrypt:
  key: ${ENCRYPT_KEY}